name: docsnap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Database
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.39

  # State Management
  flutter_riverpod: ^2.6.1

  # Document Scanner
  cunning_document_scanner: ^1.2.3

  # PDF Generation
  pdf: ^3.11.3
  printing: ^5.14.2

  # File Storage
  path_provider: ^2.1.5
  path: ^1.9.1

  # Permissions
  permission_handler: ^12.0.1

  # IDs
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Database
  drift_dev: ^2.28.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true